# Use a lightweight Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY key.json /app/key.json
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/key.json"

# Copy all source code
COPY . .

# Create uploads folder
RUN mkdir -p uploads

# Expose the port Cloud Run expects
EXPOSE 8080

# Start the app
CMD ["python", "app.py"]
